In [1]:
import sys
sys.path.append('/Users/johnkucharski/Documents/source/functionalflows')
import operator

import metric
import utilities

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/johnkucharski/Documents/source/functionalflows/data/example.csv', names=['dates', 'flows'], parse_dates=['dates'])
m1 = metric.Metric(df['dates'][0:10], np.array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1]),
                   [metric.timing(start=50, end=100), 
                    metric.magnitude(threshold=0, operator=operator.gt),
                    metric.duration(n_periods=2)])
print(m1.output)

[[1 1 0]
 [1 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [1 0 0]
 [1 1 0]
 [1 0 0]
 [0 0 0]
 [0 1 0]]


In [3]:
df = pd.read_csv('/Users/johnkucharski/Documents/source/functionalflows/data/example.csv', names=['dates', 'flows'], parse_dates=['dates'])
m2 = metric.Metric(df['dates'], df['flows'].to_numpy(), 
                   [metric.timing(start=50, end=150), 
                    metric.magnitude(threshold=0, operator=operator.gt),
                    metric.duration(n_periods=2)])
print(m2.output)

[[1 1 0]
 [1 1 0]
 [1 1 0]
 ...
 [0 0 0]
 [0 0 0]
 [0 0 0]]
